= Bluespec MCU - A Minimal Footprint RISC-V RV32IM Core
:icons: font
:data-uri:

The MCU is a low-footprint{empty}footnote:[Sub-2000 LUT base implementation] 32-bit RISC-V CPU that implements the RV32IMC subset of the RISC-V ISA.
It implements a sub-set of machine mode CSRs for exception handling and cycle counting.
The MCU uses separate instruction and data memories that are tightly coupled to the CPU. 
The MCU processor family supports multiple RISC-V architectures.

All the hardware designs in this repository are written in BSV, an HLHDL (High-Level Hardware Description Language).
BSV sources files have extension `.bsv`.
These are compiled to standard synthesizable Verilog RTL using the free and open source _bsc_ compiler
(https://github.com/B-Lang-org/bsc[]).

This repository may be used to generate MCUs that implement `rv32i[m][c]` architectures. 
When the architecture is a variable in a command line, it is referred to as `<A>` in this document.

This package supports MCUs with different TCM sizes: 8KB, 16KB, 32KB, 64KB, and 128KB.
When the TCM size is a variable (in KB) and is represented by `<M>` in this document. 

The CPU interface to the SoC uses an AHBL (AHB Lite) bus.
When the fabric is a variable is represented by `<F>` in this document.

This repository also includes reference designs that simulate in verilator, or execute on the Arty A7-100T board.

NOTE: `$MCU_REPO` points to the base of this repository (the directory where this document resides), and `$MCU_INSTALL` points to `$MCU_REPO/releases/mcu_yyyymmdd`.

== Step {counter:installSteps}: Install RISC-V Toolchain and Verilator 
Install the RISC-V toolchain. 
The Bluespec RISC-V MCU Toolchain is available for several recent Linux distributions at:

https://info.bluespec.com/mcuevaldownload?submissionGuid=aa21ef17-c2d0-45b6-93e6-a35c4c468e7e

Please follow the installation instructions for one of the Linux options provided at the above link.

NOTE: The RISC-V toolchain will install to `/opt/bluespec.`

Install Verilator:
The simulations demonstrated in this release release require Verilator 4.010 or later. Verilator comes pre-installed with certain Linux distributions like Ubuntu.
If you need to install Verilator, please see: https://verilator.org/guide/latest/install.html

== Step {counter:installSteps}: Install bsc
Compiler, simulator and tools for the Bluespec Hardware Description Language are available at (https://github.com/B-Lang-org/bsc[]). 

== Step {counter:installSteps}: Install submodules
This repository uses submodules. Please ensure that you are able to clone the submodules recursively. 

```
$ cd $MCU_REPO
$ git submodule update --init --recursive
```

== Step {counter:installSteps}: Building the MCU from source

This repository can be used to generate several different configurations of the MCU CPU.
The `build/Makefile.rv32imc.DM` makefile is configured to generate MCUs that:

* implement the RV32IMC architecture
* implement a serial multiplier and a logarithmic shifter
* implement a minimal set of CSRs for exception handling
* use the AHB-L protocol to access memory-mapped IO
* support different TCM sizes ranging from 8 KB to 128 KB
* support back-door loading of the TCMs via a loader interface
* support integration with a RISC-V Debug Module (also included in this repository)

The makefile implements the following targets:

[cols="15,~"]
|===
| Target             | Description
| `compile_core`     | Compiles the MCU CPU and generates the `mkBSCore`. RTL created in `Core_RTL`. The make variable `MEMSIZE` can be used used to change the TCM size. The default value is 16KB.
| `compile_dm`       | Compiles the RISC-V Debug Module and generates the `mkBSDebug`. RTL created in `DM_RTL`
| `compile_plic`     | Compiles the RISC-V PLIC and generates the `mkPLIC_16_1_7`. RTL created in `PLIC_RTL`. The PLIC is configured to have 16 source interrupts, 1 target interrupt and 7 priority levels.
| `compile_clint`    | Compiles the RISC-V CLINT and generates the `mkCLINT_AHBL`. RTL created in `PLIC_RTL`. The PLIC is configured to have 16 source interrupts, 1 target interrupt and 7 priority levels.
| `compile_soc`      | Compiles a test SoC that integrates `mkBSCore`, `mkBSDebug`, a loader device and a GPIO device. This SoC is also used as the demo SoC on the Arty board. RTL created in `SoC_RTL`.
| `compile_sim`      | Compiles a simulation version of the test SoC that can run on Verilator 
| `compile_sim_clint`| Compiles a simulation version of the test SoC that also integrates the CLINT
| `compile_sim_plic` | Compiles a simulation version of the test SoC that also integrates the PLIC
|===

The `make` commands must be executed from the `build` directory only and the environment variable `MCU_REPO` must be set to the base of this repository.
For instance, to compile the MCU with 32KB ITCM and DTCM:

```
$ export MCU_REPO=$(pwd)
$ cd build
$ make -f Makefile.rv32imc.DM MEMSIZE=32K compile_core
$ # To compile the debug module
$ make -f Makefile.rv32imc.DM compile_dm
```

=== Step {counter:installSteps}: Using pre-built configurations
Pre-built configurations of the MCU, Debug Module, PLIC and CLINT are available in the included release, `releases/mcu_yyyymmdd`.
In order to use the pre-built configurations please refer to the README in `releases/mcu_yyyymmdd`. Please note that the variable `MCU_INSTALL` must be set to the location of the release folder before running any of the scripts.

=== Directory Structure

```
$MCU_REPO
|
 `--- CLINT          # CLINT source
|
 `--- PLIC           # PLIC source
|
 `--- Debug_Module   # Debug module source
|
 `--- MCU_Core       # MCU source
|     |
|      `--- Core
|     |
|      `--- CPU
|     |
|      `--- ISA
|     |
|      `--- RegFiles 
|     |
|      `--- Sys
|     |
|      `--- BSV_Additional_Libs
|
 `--- Tiny_TCM       # TCM-based memory source
|
 `--- releases       # Packaged releases for a quick start
|
 `--- build          # Compile BSV and genererate RTL

```
