= Bluespec MCU - A Minimal Footprint RISC-V RV32IM Core
:icons: font
:data-uri:

The low-footprint RISC-V core is a sub-2000 LUT 32-bit RISC-V CPU that implements the RV32IMC subset of the RISC-V ISA.
It implements a sub-set of machine mode CSRs for exception handling and cycle counting.
Instruction fetches and data loads and store access a shared, 32-bit wide TCM.

The MCU processor family supports multiple RISC-V architectures.

This package contains MCUs with `rv32ic` and `rv32imc` architectures. 
When the architecture is a variable in a command line, it is referred to as `<A>` in this document.

This package contains MCUs with different TCM sizes: 8KB, 16KB, 32KB, 64KB, and 128KB.
The TCM size is a variable (in KB) and is represented by `<M>` in this document. 

The CPU interface to the SoC uses an AHBL (AHB Lite) bus.
The fabric when it is a variable is represented by `<F>` in this document.

This release includes three reference systems.
The reference system integrates a GPIO or a CLINT or a PLIC with the CPU on AHBL.
Reading and writing the GPIO is done through ordinary load and store instructions interpreted as accesses to memory-mapped IO by the CPU.

== Bluespec MCU Installation

== Step {counter:relInstall}: Install RISC-V Toolchain and Verilator 
Install The RISC-V toolchain. 
The Bluespec RISC-V MCU Toolchain is available at: https://info.bluespec.com/mcuevaldownload?submissionGuid=aa21ef17-c2d0-45b6-93e6-a35c4c468e7e

```
$ sudo yum install riscvachronix-1.202105.0.1.1.1centos7-2.x86_64.rpm
```
Install extra Verilator dependencies
```
$ sudo yum install lstdc++-stable
$ sudo yum install lstdc++-static
$ sudo yum install libstdc++-static
$ sudo yum install glibc-static
```
NOTE: The RISC-V toolchain and Verilator will install to `/opt/bluespec.`

=== Step {counter:relInstall}: Untar the release package
Download `bluespec_mcu_yyyymmdd.tar.gz` and untar the package in a directory of your choice.
Next, change directories to `mcu_yyyymmdd` and set the new environment variable `MCU_INSTALL` to the current working directory.
For instance, if the release package is `bluespec_mcu_yyyymmdd.tar.gz`:

```
$ cd <your_work_dir>
$ tar -xzvf bluespec_mcu_yyyymmdd.tar.gz
$ cd mcu_yyyymmdd
$ export MCU_INSTALL=$(pwd)
```
The variable `MCU_INSTALL` is used in the remainder of this document to identify the installation directory unambiguously.

If this release is already part of the `MCU_REPO` then an untar is not necessary, and `MCU_INSTALL` can directly be set to the releases/mcu_yyyymmdd directory.

==== Directory Structure

```
$MCU_INSTALL
|
`-- MCU.<A>.<M>K.<F>.DM : MCU (with debug module) (<A> = RV arch)
|   |                     (<M> = mem-size KB)     (<F> = SoC Fabric)
|   |
|   `-- Sim_RTL         : RTL including top-level sources for sim
|   |
|   `-- Synth_RTL       : MCU IP RTL
|   |
|   `-- Demo_RTL        : RTL to integrate MCU with demo SoC
|   |
|   `-- run             : GDB and openocd run scripts
|
`-- CLINT_AHBL          : Core Level Interrupt Controller packagd as Vivado IP
|
`-- PLIC_AHBL           : Platform Level Interrupt Controller packagd as Vivado IP
|
`-- Debug_Module        : RISC-V Debug Module pacakged as Viviado IP
|
`-- scripts             : makefiles and utilites
|
`-- tests               : C software applications (blinky)
|
`-- synth               : Wrapper-based synthesis setup for performance-area analysis
|
`-- demo                : Demo of MCU running on a test SoC on the Arty A7-100 board

```

=== Step {counter:relInstall}: Running the Arty demo

The demo integrates a MCU with 16KB TCMs (mkBSCore) with the RISC-V Debug Module (mkBSDebug), a GPIO device (mkGPIO_AHBL) and a Loader device (mkLoader).
The SoC is constructed using Vivado block design.

To run the demo, program the pre-built bit file (`run/arty.bit`) into the Arty FPGA.
```
$ cd $MCU_INSTALL/demo/run
$ ../scripts/program_fpga arty.bit
```

Once the programming completes, the `LD0` LED will blink on the board. This indicates that the loader successfully loaded a simple program into the TCMs that makes the `LD0` LED blink slowly.

To interact with the CPU or perhaps load another program via GDB, connect GDB and halt the CPU:

```
$ cd $MCU_INSTALL/demo/run
$ riscv32-unknown-elf-gdb --command init_32.gdb
```

A GDB prompt will appear and you can interact with the MCU using GDB including querying registers, loading another program, etc.

=== Rebuilding the demo project

The demo is also meant to serve as a reference on integrating the mkBSDebug and mkBSCore modules and their integration into a larger system. In order to access the Vivado block design, first create the Vivado project for the demo SoC and then open the block design using Vivado.

```
$ cd $MCU_INSTALL/demo
$ ./scripts/create_soc_project -p demo_soc
$ vivado ./demo_soc/demo_soc.xpr
```

To build the bitfile using the above project:

```
$ cd $MCU_INSTALL/demo
$ ./scripts/build_bitstream -p demo_soc
```

=== Step {counter:relInstall}: Compile the blinky RISC-V program

`blinky` is a simple program that cycles through 16 LED combinations and communicates other tests statuses through RGB LEDs. Additionally, it also runs a little sort routine to test TCM reads and writes.

```
$ export PATH=/opt/bluespec/riscvtoolchain-1.202109.2.1/bin:"$PATH"
$ cd $MCU_INSTALL/tests/blinky
$ make all <IBASE_ADDR=0xC0000000> <DBASE_ADDR=0xC8000000> <ARCH=<A>>
$ make main.text  #(optional to build disassembly)
$ make size #(optional to check the size of the generated elf)
```

The same instructions can be used to compile the other test programs -- `clint_smoketest` and `plic_smoketest`.

NOTE: Changing the `DLY` value in `$MCU_INSTALL/tests/blinky/main.c` will alter the length of the delay loops. You can use this mechanism to vary `blinky`'s overall run-time.

=== Step {counter:relInstall}: Run the GPIO blinky simulation

Three demo SoCs have been included in this release package to demonstrate MCU functionality. These SoCs integrate the MCU with an AHBL-based GPIO (`Sim_RTL`), AHBL-based PLIC (`Sim_PLIC_RTL`), and AHBL-based CLINT (`Sim_CLINT_RTL`) devices.
In the case of the demo SoC that features the PLIC, there is an interrupt injector device that injects interrupts into the PLIC to demonstrate PLIC functionality. 
Please note that to exercise these demo SoCs, the appropriate smoke-tests should be run with the appropriate demo SoC.
The `blinky` test runs on `Sim_RTL`, `plic_smoketest` runs on `Sim_PLIC_RTL` and `clint_smoketest` runs on `Sim_CLINT_RTL`.

==== Building new simulators

`MCU_INSTALL/scripts/makefiles` contains a sample makefile to build your simulators using Verilator.
If you are adding/modifying RTL files, add them to `Sim_RTL` (or `Sim_CLINT_RTL` or `Sim_PLIC_RTL`) before proceeding with the `make.`

If you are adding new C routines, you need to add the appropriate DPI calls to `Verilator_resources/src_C.`

```
$ cd $MCU_INSTALL/MCU.<A>.<M>K.<F> # Will also work for MCU.<A>.<M>K.<F>.DM
$ make simulator <SIM_RTL=Sim_RTL/Sim_PLIC_RTL/Sim_CLINT_RTL>
```

The `make` will build a simulator executable called `exe_HW_sim`.
It uses the RTL and testbench files from the directory pointed to in the Makefile variable, `SIM_RTL`. The default value is `Sim_RTL`.


==== Simulating MCU with Debug Module

Simulating with GDB involves two terminals.
We will use the pre-built Verilator simulator, `exe_HW_sim,` to simulate the MCU SoC, using the blinky program compiled in <<Step 3: Compile the blinky RISC-V program>> as the software application.

The simulation starts and opens a connection on TCP port `5555` listening for a connection from GDB. The MCU is however not halted and after reset starts executing the program in the TCM which is loaded with the contents of `/tmp/tcm.mem.`

In the first terminal, run the same make command as shown in <<Simulating MCU with no Debug Module>> (the example assumes a system with 16KB TCM that uses AHBL):

```
$ cd $MCU_INSTALL/MCU.16K.AHBL.DM
$ make run_test TEST=$MCU_INSTALL/tests/blinky/main MEMSIZE=16
```

In the second terminal:
```
$ cd $MCU_INSTALL/MCU.16K.AHBL.DM/run
$ riscv32-unknown-elf-gdb --command init_32.gdb
```

Once GDB establishes a connection with the debug module integrated with the MCU, the core is halted, and you can interact with the MCU using the standard GDB commands.
The included script `init_32.gdb` is for reference only and may be changed freely as per your needs.

NOTE: To end the simulation, exit from GDB first before entering `Ctrl+C` in the simulator window; this ensures that the openocd connection connection is gracefully terminated.

NOTE: To dump a VCD waveform of the simulation, use the target `run_test_waves` in the make command. 

NOTE: Make sure that the hardware simulation does not auto-terminate before a GDB connection can be established. A simple way to do so would be to add a delay loop of sufficient length to the test.

=== The SoC address map

The ITCM is placed at `0xc0000000` and the DTCM is placed at `0xc8000000`. These locations are fixed in this release.
The PC and MTVEC reset to `0xc0000000`.
The PLIC is placed at `0x0c000000` and the CLINT is placed at `0x02000000`.

There are three interrupt inputs to `mkMCUTop` -- external (`ext_interrupt), software (`sw_interrupt`) and timer (`timer_interrupt`).
While integrating, the corresponding input must be tied low if an interrupts are not being used.

The mkMCUTop drives all AHB-Lite master signals.

The RAM blocks in the TCM expects two 32-bit hex file, `/tmp/itcm.mem` and `/tmp/dtcm.mem`, to be present during synthesis; if these files are not present, the contents of the TCM RAM after synthesis is undefined.
The simplest way to generate these files is to run the application program in simulation, which runs `Elf_to_Hex` on the elf file and creates the memory hex files.
The utility `$MCU_INSTALL/scripts/Elf_to_Hex/elfhex.sh` utility can also be run directly without proceeding to simulation.

All sources to synthesize `mkMCUTop.v` are present in the `MCU.<A>.<M>K.<F>/Synth_RTL` and `MCU.<A>.<M>K.<F>.DM/Synth_RTL` directories. 

==== Demo SoC (simulation)

Three demo SoCs have been included in the release package to demonstrate MCU functionality. These SoCs integrate the MCU with an AHBL-based GPIO (`Sim_RTL`), AHBL-based PLIC (`Sim_PLIC_RTL`), and AHBL-based CLINT (`Sim_CLINT_RTL`) devices. 
In the case of the demo SoC, which features the PLIC, there is an interrupt injector device that injects interrupts into the PLIC to demonstrate PLIC functionality.  

The top level of the demo SoC is `mkSoC_Top.v.`

==== Wrapper Based Synthesis Setup

The `synth` directory has synthesis scripts for running on Xilinx and Microsemi devices.
The run script, `run_synth.sh` takes as an input the top-level of the synthesis hierarchy and wraps a shift register around its pins so that all timing paths within the design can be analyzed as register to register paths.
Furthermore, it prevents the synthesis tools from optimizing away any logic inside the synthesis hierarchy due to unconnected inputs.

In the following examples, let's assume that we want to synthesize the design in `MCU.64K.AHBL.DM`, and our hierarchy of interest is the complete design - the top-level is `mkMCUTop.`

===== Synthesizing for Xilinx Devices

These scripts have been tested with Vivado 2019.1.
Let's assume we are synthesizing for a clock frequency of 100 MHz (10 ns clock period), using the default board/device (Arty A7-100).

```
$ cd $MCU_INSTALL/synth/xilinx
$ ./run_synth.sh -c 10.0 -t mkMCUTop -f $MCU_INSTALL/MCU.rv32imc.64K.AHBL.DM/Synth_RTL -j 4 
```

The last argument, `-j 4`, instructs Vivado to run up to four jobs in parallel.
A complete list of `run_synth.sh` options are available with `run_synth.sh --help`

Vivado runs inside a synthesis work area created by `run_synth.sh`.
This work area will be named like `synth-mkMCUTop-datestamp.`
The log files from the run will be placed in the `impl_1` directory inside the synthesis run directory.
A sampling of frequency and utilization numbers for rv32imc configurations without the debug module are tabulated below.

.Timing on Xilinx
[cols="30,20,15,~"]
|===
| Configuration              | Fmax (MHz)   | LUTs   | DFFs

| MCU.rv32imc.16K.AHBL       | 94.06        | 2951   | 1388

| MCU.rv32imc.32K.AHBL       | 95.35        | 3015   | 1390

| MCU.rv32imc.64K.AHBL       | 87.48        | 2997   | 1385

| MCU.rv32imc.128K.AHBL      | 87.08        | 2975   | 1387

|===

===== Synthesizing for Microsemi Devices

These scripts have been tested with Libero SoC v12.6. 
In the example below, we are synthesizing for a clock frequency of 50 MHz (20 ns clock period).
The FPGA device in these scripts has been fixed to SmartFusion2 M2S090T FPGA.

```
$ cd $MCU_INSTALL/synth/microsemi
$ ./run_synth.sh -c 20.0 -t mkMCUTop -f $MCU_INSTALL/MCU.rv32ic.64K.AHBL.DM/Synth_RTL
```

Libero runs inside a synthesis work-area created by `run_synth.sh`.
This work area will be named like `synth-mkMCUTop-datestamp`.
The log files from the run will be placed in the `mkMCUTop` directory inside the synthesis run directory.
