//
// Generated by Bluespec Compiler, version 2021.12.1-27-g9a7d5e05 (build 9a7d5e05)
//
//
// Ports:
// Name                         I/O  size props
// RDY_dmi_read_addr              O     1
// dmi_read_data                  O    32
// RDY_dmi_read_data              O     1
// RDY_dmi_write                  O     1
// hart0_hart_reset_client_request_get  O     1 reg
// RDY_hart0_hart_reset_client_request_get  O     1 reg
// RDY_hart0_hart_reset_client_response_put  O     1 reg
// hart0_hart_client_run_halt_request_get  O     1 reg
// RDY_hart0_hart_client_run_halt_request_get  O     1 reg
// RDY_hart0_hart_client_run_halt_response_put  O     1 reg
// hart0_hart_get_other_req_get   O     4 reg
// RDY_hart0_hart_get_other_req_get  O     1 reg
// hart0_hart_gpr_mem_client_request_get  O    38 reg
// RDY_hart0_hart_gpr_mem_client_request_get  O     1 reg
// RDY_hart0_hart_gpr_mem_client_response_put  O     1 reg
// hart0_hart_csr_mem_client_request_get  O    45 reg
// RDY_hart0_hart_csr_mem_client_request_get  O     1 reg
// RDY_hart0_hart_csr_mem_client_response_put  O     1 reg
// ndm_reset_client_request_get   O     1 reg
// RDY_ndm_reset_client_request_get  O     1 reg
// RDY_ndm_reset_client_response_put  O     1 reg
// sb_client_request_get          O    68 reg
// RDY_sb_client_request_get      O     1 reg
// RDY_sb_client_response_put     O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// dmi_read_addr_dm_addr          I     7
// dmi_write_dm_addr              I     7
// dmi_write_dm_word              I    32
// hart0_hart_reset_client_response_put  I     1 reg
// hart0_hart_client_run_halt_response_put  I     1 reg
// hart0_hart_gpr_mem_client_response_put  I    33 reg
// hart0_hart_csr_mem_client_response_put  I    33 reg
// ndm_reset_client_response_put  I     1 reg
// sb_client_response_put         I    34 reg
// EN_dmi_read_addr               I     1
// EN_dmi_write                   I     1
// EN_hart0_hart_reset_client_response_put  I     1
// EN_hart0_hart_client_run_halt_response_put  I     1
// EN_hart0_hart_gpr_mem_client_response_put  I     1
// EN_hart0_hart_csr_mem_client_response_put  I     1
// EN_ndm_reset_client_response_put  I     1
// EN_sb_client_response_put      I     1
// EN_dmi_read_data               I     1
// EN_hart0_hart_reset_client_request_get  I     1
// EN_hart0_hart_client_run_halt_request_get  I     1
// EN_hart0_hart_get_other_req_get  I     1
// EN_hart0_hart_gpr_mem_client_request_get  I     1
// EN_hart0_hart_csr_mem_client_request_get  I     1
// EN_ndm_reset_client_request_get  I     1
// EN_sb_client_request_get       I     1
//
// Combinational paths from inputs to outputs:
//   (dmi_read_addr_dm_addr, EN_dmi_read_addr) -> RDY_dmi_read_data
//   (dmi_read_addr_dm_addr, EN_dmi_read_addr, EN_dmi_read_data) -> dmi_read_data
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkDebug_Module(CLK,
		      RST_N,

		      dmi_read_addr_dm_addr,
		      EN_dmi_read_addr,
		      RDY_dmi_read_addr,

		      EN_dmi_read_data,
		      dmi_read_data,
		      RDY_dmi_read_data,

		      dmi_write_dm_addr,
		      dmi_write_dm_word,
		      EN_dmi_write,
		      RDY_dmi_write,

		      EN_hart0_hart_reset_client_request_get,
		      hart0_hart_reset_client_request_get,
		      RDY_hart0_hart_reset_client_request_get,

		      hart0_hart_reset_client_response_put,
		      EN_hart0_hart_reset_client_response_put,
		      RDY_hart0_hart_reset_client_response_put,

		      EN_hart0_hart_client_run_halt_request_get,
		      hart0_hart_client_run_halt_request_get,
		      RDY_hart0_hart_client_run_halt_request_get,

		      hart0_hart_client_run_halt_response_put,
		      EN_hart0_hart_client_run_halt_response_put,
		      RDY_hart0_hart_client_run_halt_response_put,

		      EN_hart0_hart_get_other_req_get,
		      hart0_hart_get_other_req_get,
		      RDY_hart0_hart_get_other_req_get,

		      EN_hart0_hart_gpr_mem_client_request_get,
		      hart0_hart_gpr_mem_client_request_get,
		      RDY_hart0_hart_gpr_mem_client_request_get,

		      hart0_hart_gpr_mem_client_response_put,
		      EN_hart0_hart_gpr_mem_client_response_put,
		      RDY_hart0_hart_gpr_mem_client_response_put,

		      EN_hart0_hart_csr_mem_client_request_get,
		      hart0_hart_csr_mem_client_request_get,
		      RDY_hart0_hart_csr_mem_client_request_get,

		      hart0_hart_csr_mem_client_response_put,
		      EN_hart0_hart_csr_mem_client_response_put,
		      RDY_hart0_hart_csr_mem_client_response_put,

		      EN_ndm_reset_client_request_get,
		      ndm_reset_client_request_get,
		      RDY_ndm_reset_client_request_get,

		      ndm_reset_client_response_put,
		      EN_ndm_reset_client_response_put,
		      RDY_ndm_reset_client_response_put,

		      EN_sb_client_request_get,
		      sb_client_request_get,
		      RDY_sb_client_request_get,

		      sb_client_response_put,
		      EN_sb_client_response_put,
		      RDY_sb_client_response_put);
  input  CLK;
  input  RST_N;

  // action method dmi_read_addr
  input  [6 : 0] dmi_read_addr_dm_addr;
  input  EN_dmi_read_addr;
  output RDY_dmi_read_addr;

  // actionvalue method dmi_read_data
  input  EN_dmi_read_data;
  output [31 : 0] dmi_read_data;
  output RDY_dmi_read_data;

  // action method dmi_write
  input  [6 : 0] dmi_write_dm_addr;
  input  [31 : 0] dmi_write_dm_word;
  input  EN_dmi_write;
  output RDY_dmi_write;

  // actionvalue method hart0_hart_reset_client_request_get
  input  EN_hart0_hart_reset_client_request_get;
  output hart0_hart_reset_client_request_get;
  output RDY_hart0_hart_reset_client_request_get;

  // action method hart0_hart_reset_client_response_put
  input  hart0_hart_reset_client_response_put;
  input  EN_hart0_hart_reset_client_response_put;
  output RDY_hart0_hart_reset_client_response_put;

  // actionvalue method hart0_hart_client_run_halt_request_get
  input  EN_hart0_hart_client_run_halt_request_get;
  output hart0_hart_client_run_halt_request_get;
  output RDY_hart0_hart_client_run_halt_request_get;

  // action method hart0_hart_client_run_halt_response_put
  input  hart0_hart_client_run_halt_response_put;
  input  EN_hart0_hart_client_run_halt_response_put;
  output RDY_hart0_hart_client_run_halt_response_put;

  // actionvalue method hart0_hart_get_other_req_get
  input  EN_hart0_hart_get_other_req_get;
  output [3 : 0] hart0_hart_get_other_req_get;
  output RDY_hart0_hart_get_other_req_get;

  // actionvalue method hart0_hart_gpr_mem_client_request_get
  input  EN_hart0_hart_gpr_mem_client_request_get;
  output [37 : 0] hart0_hart_gpr_mem_client_request_get;
  output RDY_hart0_hart_gpr_mem_client_request_get;

  // action method hart0_hart_gpr_mem_client_response_put
  input  [32 : 0] hart0_hart_gpr_mem_client_response_put;
  input  EN_hart0_hart_gpr_mem_client_response_put;
  output RDY_hart0_hart_gpr_mem_client_response_put;

  // actionvalue method hart0_hart_csr_mem_client_request_get
  input  EN_hart0_hart_csr_mem_client_request_get;
  output [44 : 0] hart0_hart_csr_mem_client_request_get;
  output RDY_hart0_hart_csr_mem_client_request_get;

  // action method hart0_hart_csr_mem_client_response_put
  input  [32 : 0] hart0_hart_csr_mem_client_response_put;
  input  EN_hart0_hart_csr_mem_client_response_put;
  output RDY_hart0_hart_csr_mem_client_response_put;

  // actionvalue method ndm_reset_client_request_get
  input  EN_ndm_reset_client_request_get;
  output ndm_reset_client_request_get;
  output RDY_ndm_reset_client_request_get;

  // action method ndm_reset_client_response_put
  input  ndm_reset_client_response_put;
  input  EN_ndm_reset_client_response_put;
  output RDY_ndm_reset_client_response_put;

  // actionvalue method sb_client_request_get
  input  EN_sb_client_request_get;
  output [67 : 0] sb_client_request_get;
  output RDY_sb_client_request_get;

  // action method sb_client_response_put
  input  [33 : 0] sb_client_response_put;
  input  EN_sb_client_response_put;
  output RDY_sb_client_response_put;

  // signals for module outputs
  reg [31 : 0] dmi_read_data;
  wire [67 : 0] sb_client_request_get;
  wire [44 : 0] hart0_hart_csr_mem_client_request_get;
  wire [37 : 0] hart0_hart_gpr_mem_client_request_get;
  wire [3 : 0] hart0_hart_get_other_req_get;
  wire RDY_dmi_read_addr,
       RDY_dmi_read_data,
       RDY_dmi_write,
       RDY_hart0_hart_client_run_halt_request_get,
       RDY_hart0_hart_client_run_halt_response_put,
       RDY_hart0_hart_csr_mem_client_request_get,
       RDY_hart0_hart_csr_mem_client_response_put,
       RDY_hart0_hart_get_other_req_get,
       RDY_hart0_hart_gpr_mem_client_request_get,
       RDY_hart0_hart_gpr_mem_client_response_put,
       RDY_hart0_hart_reset_client_request_get,
       RDY_hart0_hart_reset_client_response_put,
       RDY_ndm_reset_client_request_get,
       RDY_ndm_reset_client_response_put,
       RDY_sb_client_request_get,
       RDY_sb_client_response_put,
       hart0_hart_client_run_halt_request_get,
       hart0_hart_reset_client_request_get,
       ndm_reset_client_request_get;

  // inlined wires
  wire [7 : 0] f_read_addr_rv$port0__write_1,
	       f_read_addr_rv$port1__read,
	       f_read_addr_rv$port2__read;

  // register f_read_addr_rv
  reg [7 : 0] f_read_addr_rv;
  wire [7 : 0] f_read_addr_rv$D_IN;
  wire f_read_addr_rv$EN;

  // ports of submodule dm_abstract_commands
  wire [44 : 0] dm_abstract_commands$hart0_csr_mem_client_request_get;
  wire [37 : 0] dm_abstract_commands$hart0_gpr_mem_client_request_get;
  wire [32 : 0] dm_abstract_commands$hart0_csr_mem_client_response_put,
		dm_abstract_commands$hart0_gpr_mem_client_response_put;
  wire [31 : 0] dm_abstract_commands$av_read,
		dm_abstract_commands$write_dm_word;
  wire [6 : 0] dm_abstract_commands$av_read_dm_addr,
	       dm_abstract_commands$write_dm_addr;
  wire dm_abstract_commands$EN_av_read,
       dm_abstract_commands$EN_hart0_csr_mem_client_request_get,
       dm_abstract_commands$EN_hart0_csr_mem_client_response_put,
       dm_abstract_commands$EN_hart0_gpr_mem_client_request_get,
       dm_abstract_commands$EN_hart0_gpr_mem_client_response_put,
       dm_abstract_commands$EN_reset,
       dm_abstract_commands$EN_write,
       dm_abstract_commands$RDY_hart0_csr_mem_client_request_get,
       dm_abstract_commands$RDY_hart0_csr_mem_client_response_put,
       dm_abstract_commands$RDY_hart0_gpr_mem_client_request_get,
       dm_abstract_commands$RDY_hart0_gpr_mem_client_response_put;

  // ports of submodule dm_run_control
  wire [31 : 0] dm_run_control$av_read, dm_run_control$write_dm_word;
  wire [6 : 0] dm_run_control$av_read_dm_addr, dm_run_control$write_dm_addr;
  wire [3 : 0] dm_run_control$hart0_get_other_req_get;
  wire dm_run_control$EN_av_read,
       dm_run_control$EN_hart0_client_run_halt_request_get,
       dm_run_control$EN_hart0_client_run_halt_response_put,
       dm_run_control$EN_hart0_get_other_req_get,
       dm_run_control$EN_hart0_reset_client_request_get,
       dm_run_control$EN_hart0_reset_client_response_put,
       dm_run_control$EN_ndm_reset_client_request_get,
       dm_run_control$EN_ndm_reset_client_response_put,
       dm_run_control$EN_reset,
       dm_run_control$EN_write,
       dm_run_control$RDY_hart0_client_run_halt_request_get,
       dm_run_control$RDY_hart0_client_run_halt_response_put,
       dm_run_control$RDY_hart0_get_other_req_get,
       dm_run_control$RDY_hart0_reset_client_request_get,
       dm_run_control$RDY_hart0_reset_client_response_put,
       dm_run_control$RDY_ndm_reset_client_request_get,
       dm_run_control$RDY_ndm_reset_client_response_put,
       dm_run_control$RDY_write,
       dm_run_control$dmactive,
       dm_run_control$hart0_client_run_halt_request_get,
       dm_run_control$hart0_client_run_halt_response_put,
       dm_run_control$hart0_reset_client_request_get,
       dm_run_control$hart0_reset_client_response_put,
       dm_run_control$ndm_reset_client_request_get,
       dm_run_control$ndm_reset_client_response_put;

  // ports of submodule dm_system_bus
  wire [67 : 0] dm_system_bus$master_request_get;
  wire [33 : 0] dm_system_bus$master_response_put;
  wire [31 : 0] dm_system_bus$av_read, dm_system_bus$write_dm_word;
  wire [6 : 0] dm_system_bus$av_read_dm_addr, dm_system_bus$write_dm_addr;
  wire dm_system_bus$EN_av_read,
       dm_system_bus$EN_master_request_get,
       dm_system_bus$EN_master_response_put,
       dm_system_bus$EN_reset,
       dm_system_bus$EN_write,
       dm_system_bus$RDY_av_read,
       dm_system_bus$RDY_master_request_get,
       dm_system_bus$RDY_master_response_put,
       dm_system_bus$RDY_write;

  // rule scheduling signals
  wire CAN_FIRE_RL_rl_reset,
       CAN_FIRE_dmi_read_addr,
       CAN_FIRE_dmi_read_data,
       CAN_FIRE_dmi_write,
       CAN_FIRE_hart0_hart_client_run_halt_request_get,
       CAN_FIRE_hart0_hart_client_run_halt_response_put,
       CAN_FIRE_hart0_hart_csr_mem_client_request_get,
       CAN_FIRE_hart0_hart_csr_mem_client_response_put,
       CAN_FIRE_hart0_hart_get_other_req_get,
       CAN_FIRE_hart0_hart_gpr_mem_client_request_get,
       CAN_FIRE_hart0_hart_gpr_mem_client_response_put,
       CAN_FIRE_hart0_hart_reset_client_request_get,
       CAN_FIRE_hart0_hart_reset_client_response_put,
       CAN_FIRE_ndm_reset_client_request_get,
       CAN_FIRE_ndm_reset_client_response_put,
       CAN_FIRE_sb_client_request_get,
       CAN_FIRE_sb_client_response_put,
       WILL_FIRE_RL_rl_reset,
       WILL_FIRE_dmi_read_addr,
       WILL_FIRE_dmi_read_data,
       WILL_FIRE_dmi_write,
       WILL_FIRE_hart0_hart_client_run_halt_request_get,
       WILL_FIRE_hart0_hart_client_run_halt_response_put,
       WILL_FIRE_hart0_hart_csr_mem_client_request_get,
       WILL_FIRE_hart0_hart_csr_mem_client_response_put,
       WILL_FIRE_hart0_hart_get_other_req_get,
       WILL_FIRE_hart0_hart_gpr_mem_client_request_get,
       WILL_FIRE_hart0_hart_gpr_mem_client_response_put,
       WILL_FIRE_hart0_hart_reset_client_request_get,
       WILL_FIRE_hart0_hart_reset_client_response_put,
       WILL_FIRE_ndm_reset_client_request_get,
       WILL_FIRE_ndm_reset_client_response_put,
       WILL_FIRE_sb_client_request_get,
       WILL_FIRE_sb_client_response_put;

  // declarations used by system tasks
  // synopsys translate_off
  reg [31 : 0] v__h544;
  reg [31 : 0] v__h538;
  // synopsys translate_on

  // action method dmi_read_addr
  assign RDY_dmi_read_addr = !f_read_addr_rv[7] ;
  assign CAN_FIRE_dmi_read_addr = !f_read_addr_rv[7] ;
  assign WILL_FIRE_dmi_read_addr = EN_dmi_read_addr ;

  // actionvalue method dmi_read_data
  always@(f_read_addr_rv$port1__read or
	  dm_abstract_commands$av_read or
	  dm_run_control$av_read or dm_system_bus$av_read)
  begin
    case (f_read_addr_rv$port1__read[6:0])
      7'h04,
      7'h05,
      7'h06,
      7'h07,
      7'h08,
      7'h09,
      7'h0A,
      7'h0B,
      7'h0C,
      7'h0D,
      7'h0F,
      7'h16,
      7'h17,
      7'h18,
      7'h20:
	  dmi_read_data = dm_abstract_commands$av_read;
      7'h10,
      7'h11,
      7'h12,
      7'h13,
      7'h14,
      7'h15,
      7'h19,
      7'h30,
      7'h40,
      7'h5F,
      7'h60:
	  dmi_read_data = dm_run_control$av_read;
      7'h38, 7'h39, 7'h3A, 7'h3B, 7'h3C, 7'h3D, 7'h3E, 7'h3F:
	  dmi_read_data = dm_system_bus$av_read;
      default: dmi_read_data = 32'd0;
    endcase
  end
  assign RDY_dmi_read_data =
	     f_read_addr_rv$port1__read[7] &&
	     (f_read_addr_rv$port1__read[6:0] != 7'h38 &&
	      f_read_addr_rv$port1__read[6:0] != 7'h39 &&
	      f_read_addr_rv$port1__read[6:0] != 7'h3A &&
	      f_read_addr_rv$port1__read[6:0] != 7'h3B &&
	      f_read_addr_rv$port1__read[6:0] != 7'h3C &&
	      f_read_addr_rv$port1__read[6:0] != 7'h3D &&
	      f_read_addr_rv$port1__read[6:0] != 7'h3E &&
	      f_read_addr_rv$port1__read[6:0] != 7'h3F ||
	      dm_system_bus$RDY_av_read) ;
  assign CAN_FIRE_dmi_read_data =
	     f_read_addr_rv$port1__read[7] &&
	     (f_read_addr_rv$port1__read[6:0] != 7'h38 &&
	      f_read_addr_rv$port1__read[6:0] != 7'h39 &&
	      f_read_addr_rv$port1__read[6:0] != 7'h3A &&
	      f_read_addr_rv$port1__read[6:0] != 7'h3B &&
	      f_read_addr_rv$port1__read[6:0] != 7'h3C &&
	      f_read_addr_rv$port1__read[6:0] != 7'h3D &&
	      f_read_addr_rv$port1__read[6:0] != 7'h3E &&
	      f_read_addr_rv$port1__read[6:0] != 7'h3F ||
	      dm_system_bus$RDY_av_read) ;
  assign WILL_FIRE_dmi_read_data = EN_dmi_read_data ;

  // action method dmi_write
  assign RDY_dmi_write = dm_run_control$RDY_write && dm_system_bus$RDY_write ;
  assign CAN_FIRE_dmi_write =
	     dm_run_control$RDY_write && dm_system_bus$RDY_write ;
  assign WILL_FIRE_dmi_write = EN_dmi_write ;

  // actionvalue method hart0_hart_reset_client_request_get
  assign hart0_hart_reset_client_request_get =
	     dm_run_control$hart0_reset_client_request_get ;
  assign RDY_hart0_hart_reset_client_request_get =
	     dm_run_control$RDY_hart0_reset_client_request_get ;
  assign CAN_FIRE_hart0_hart_reset_client_request_get =
	     dm_run_control$RDY_hart0_reset_client_request_get ;
  assign WILL_FIRE_hart0_hart_reset_client_request_get =
	     EN_hart0_hart_reset_client_request_get ;

  // action method hart0_hart_reset_client_response_put
  assign RDY_hart0_hart_reset_client_response_put =
	     dm_run_control$RDY_hart0_reset_client_response_put ;
  assign CAN_FIRE_hart0_hart_reset_client_response_put =
	     dm_run_control$RDY_hart0_reset_client_response_put ;
  assign WILL_FIRE_hart0_hart_reset_client_response_put =
	     EN_hart0_hart_reset_client_response_put ;

  // actionvalue method hart0_hart_client_run_halt_request_get
  assign hart0_hart_client_run_halt_request_get =
	     dm_run_control$hart0_client_run_halt_request_get ;
  assign RDY_hart0_hart_client_run_halt_request_get =
	     dm_run_control$RDY_hart0_client_run_halt_request_get ;
  assign CAN_FIRE_hart0_hart_client_run_halt_request_get =
	     dm_run_control$RDY_hart0_client_run_halt_request_get ;
  assign WILL_FIRE_hart0_hart_client_run_halt_request_get =
	     EN_hart0_hart_client_run_halt_request_get ;

  // action method hart0_hart_client_run_halt_response_put
  assign RDY_hart0_hart_client_run_halt_response_put =
	     dm_run_control$RDY_hart0_client_run_halt_response_put ;
  assign CAN_FIRE_hart0_hart_client_run_halt_response_put =
	     dm_run_control$RDY_hart0_client_run_halt_response_put ;
  assign WILL_FIRE_hart0_hart_client_run_halt_response_put =
	     EN_hart0_hart_client_run_halt_response_put ;

  // actionvalue method hart0_hart_get_other_req_get
  assign hart0_hart_get_other_req_get =
	     dm_run_control$hart0_get_other_req_get ;
  assign RDY_hart0_hart_get_other_req_get =
	     dm_run_control$RDY_hart0_get_other_req_get ;
  assign CAN_FIRE_hart0_hart_get_other_req_get =
	     dm_run_control$RDY_hart0_get_other_req_get ;
  assign WILL_FIRE_hart0_hart_get_other_req_get =
	     EN_hart0_hart_get_other_req_get ;

  // actionvalue method hart0_hart_gpr_mem_client_request_get
  assign hart0_hart_gpr_mem_client_request_get =
	     dm_abstract_commands$hart0_gpr_mem_client_request_get ;
  assign RDY_hart0_hart_gpr_mem_client_request_get =
	     dm_abstract_commands$RDY_hart0_gpr_mem_client_request_get ;
  assign CAN_FIRE_hart0_hart_gpr_mem_client_request_get =
	     dm_abstract_commands$RDY_hart0_gpr_mem_client_request_get ;
  assign WILL_FIRE_hart0_hart_gpr_mem_client_request_get =
	     EN_hart0_hart_gpr_mem_client_request_get ;

  // action method hart0_hart_gpr_mem_client_response_put
  assign RDY_hart0_hart_gpr_mem_client_response_put =
	     dm_abstract_commands$RDY_hart0_gpr_mem_client_response_put ;
  assign CAN_FIRE_hart0_hart_gpr_mem_client_response_put =
	     dm_abstract_commands$RDY_hart0_gpr_mem_client_response_put ;
  assign WILL_FIRE_hart0_hart_gpr_mem_client_response_put =
	     EN_hart0_hart_gpr_mem_client_response_put ;

  // actionvalue method hart0_hart_csr_mem_client_request_get
  assign hart0_hart_csr_mem_client_request_get =
	     dm_abstract_commands$hart0_csr_mem_client_request_get ;
  assign RDY_hart0_hart_csr_mem_client_request_get =
	     dm_abstract_commands$RDY_hart0_csr_mem_client_request_get ;
  assign CAN_FIRE_hart0_hart_csr_mem_client_request_get =
	     dm_abstract_commands$RDY_hart0_csr_mem_client_request_get ;
  assign WILL_FIRE_hart0_hart_csr_mem_client_request_get =
	     EN_hart0_hart_csr_mem_client_request_get ;

  // action method hart0_hart_csr_mem_client_response_put
  assign RDY_hart0_hart_csr_mem_client_response_put =
	     dm_abstract_commands$RDY_hart0_csr_mem_client_response_put ;
  assign CAN_FIRE_hart0_hart_csr_mem_client_response_put =
	     dm_abstract_commands$RDY_hart0_csr_mem_client_response_put ;
  assign WILL_FIRE_hart0_hart_csr_mem_client_response_put =
	     EN_hart0_hart_csr_mem_client_response_put ;

  // actionvalue method ndm_reset_client_request_get
  assign ndm_reset_client_request_get =
	     dm_run_control$ndm_reset_client_request_get ;
  assign RDY_ndm_reset_client_request_get =
	     dm_run_control$RDY_ndm_reset_client_request_get ;
  assign CAN_FIRE_ndm_reset_client_request_get =
	     dm_run_control$RDY_ndm_reset_client_request_get ;
  assign WILL_FIRE_ndm_reset_client_request_get =
	     EN_ndm_reset_client_request_get ;

  // action method ndm_reset_client_response_put
  assign RDY_ndm_reset_client_response_put =
	     dm_run_control$RDY_ndm_reset_client_response_put ;
  assign CAN_FIRE_ndm_reset_client_response_put =
	     dm_run_control$RDY_ndm_reset_client_response_put ;
  assign WILL_FIRE_ndm_reset_client_response_put =
	     EN_ndm_reset_client_response_put ;

  // actionvalue method sb_client_request_get
  assign sb_client_request_get = dm_system_bus$master_request_get ;
  assign RDY_sb_client_request_get = dm_system_bus$RDY_master_request_get ;
  assign CAN_FIRE_sb_client_request_get =
	     dm_system_bus$RDY_master_request_get ;
  assign WILL_FIRE_sb_client_request_get = EN_sb_client_request_get ;

  // action method sb_client_response_put
  assign RDY_sb_client_response_put = dm_system_bus$RDY_master_response_put ;
  assign CAN_FIRE_sb_client_response_put =
	     dm_system_bus$RDY_master_response_put ;
  assign WILL_FIRE_sb_client_response_put = EN_sb_client_response_put ;

  // submodule dm_abstract_commands
  mkDM_Abstract_Commands dm_abstract_commands(.CLK(CLK),
					      .RST_N(RST_N),
					      .av_read_dm_addr(dm_abstract_commands$av_read_dm_addr),
					      .hart0_csr_mem_client_response_put(dm_abstract_commands$hart0_csr_mem_client_response_put),
					      .hart0_gpr_mem_client_response_put(dm_abstract_commands$hart0_gpr_mem_client_response_put),
					      .write_dm_addr(dm_abstract_commands$write_dm_addr),
					      .write_dm_word(dm_abstract_commands$write_dm_word),
					      .EN_reset(dm_abstract_commands$EN_reset),
					      .EN_av_read(dm_abstract_commands$EN_av_read),
					      .EN_write(dm_abstract_commands$EN_write),
					      .EN_hart0_gpr_mem_client_request_get(dm_abstract_commands$EN_hart0_gpr_mem_client_request_get),
					      .EN_hart0_gpr_mem_client_response_put(dm_abstract_commands$EN_hart0_gpr_mem_client_response_put),
					      .EN_hart0_csr_mem_client_request_get(dm_abstract_commands$EN_hart0_csr_mem_client_request_get),
					      .EN_hart0_csr_mem_client_response_put(dm_abstract_commands$EN_hart0_csr_mem_client_response_put),
					      .RDY_reset(),
					      .av_read(dm_abstract_commands$av_read),
					      .RDY_av_read(),
					      .RDY_write(),
					      .hart0_gpr_mem_client_request_get(dm_abstract_commands$hart0_gpr_mem_client_request_get),
					      .RDY_hart0_gpr_mem_client_request_get(dm_abstract_commands$RDY_hart0_gpr_mem_client_request_get),
					      .RDY_hart0_gpr_mem_client_response_put(dm_abstract_commands$RDY_hart0_gpr_mem_client_response_put),
					      .hart0_csr_mem_client_request_get(dm_abstract_commands$hart0_csr_mem_client_request_get),
					      .RDY_hart0_csr_mem_client_request_get(dm_abstract_commands$RDY_hart0_csr_mem_client_request_get),
					      .RDY_hart0_csr_mem_client_response_put(dm_abstract_commands$RDY_hart0_csr_mem_client_response_put));

  // submodule dm_run_control
  mkDM_Run_Control dm_run_control(.CLK(CLK),
				  .RST_N(RST_N),
				  .av_read_dm_addr(dm_run_control$av_read_dm_addr),
				  .hart0_client_run_halt_response_put(dm_run_control$hart0_client_run_halt_response_put),
				  .hart0_reset_client_response_put(dm_run_control$hart0_reset_client_response_put),
				  .ndm_reset_client_response_put(dm_run_control$ndm_reset_client_response_put),
				  .write_dm_addr(dm_run_control$write_dm_addr),
				  .write_dm_word(dm_run_control$write_dm_word),
				  .EN_reset(dm_run_control$EN_reset),
				  .EN_av_read(dm_run_control$EN_av_read),
				  .EN_write(dm_run_control$EN_write),
				  .EN_hart0_reset_client_request_get(dm_run_control$EN_hart0_reset_client_request_get),
				  .EN_hart0_reset_client_response_put(dm_run_control$EN_hart0_reset_client_response_put),
				  .EN_hart0_client_run_halt_request_get(dm_run_control$EN_hart0_client_run_halt_request_get),
				  .EN_hart0_client_run_halt_response_put(dm_run_control$EN_hart0_client_run_halt_response_put),
				  .EN_hart0_get_other_req_get(dm_run_control$EN_hart0_get_other_req_get),
				  .EN_ndm_reset_client_request_get(dm_run_control$EN_ndm_reset_client_request_get),
				  .EN_ndm_reset_client_response_put(dm_run_control$EN_ndm_reset_client_response_put),
				  .dmactive(dm_run_control$dmactive),
				  .RDY_dmactive(),
				  .RDY_reset(),
				  .av_read(dm_run_control$av_read),
				  .RDY_av_read(),
				  .RDY_write(dm_run_control$RDY_write),
				  .hart0_reset_client_request_get(dm_run_control$hart0_reset_client_request_get),
				  .RDY_hart0_reset_client_request_get(dm_run_control$RDY_hart0_reset_client_request_get),
				  .RDY_hart0_reset_client_response_put(dm_run_control$RDY_hart0_reset_client_response_put),
				  .hart0_client_run_halt_request_get(dm_run_control$hart0_client_run_halt_request_get),
				  .RDY_hart0_client_run_halt_request_get(dm_run_control$RDY_hart0_client_run_halt_request_get),
				  .RDY_hart0_client_run_halt_response_put(dm_run_control$RDY_hart0_client_run_halt_response_put),
				  .hart0_get_other_req_get(dm_run_control$hart0_get_other_req_get),
				  .RDY_hart0_get_other_req_get(dm_run_control$RDY_hart0_get_other_req_get),
				  .ndm_reset_client_request_get(dm_run_control$ndm_reset_client_request_get),
				  .RDY_ndm_reset_client_request_get(dm_run_control$RDY_ndm_reset_client_request_get),
				  .RDY_ndm_reset_client_response_put(dm_run_control$RDY_ndm_reset_client_response_put));

  // submodule dm_system_bus
  mkDM_System_Bus dm_system_bus(.CLK(CLK),
				.RST_N(RST_N),
				.av_read_dm_addr(dm_system_bus$av_read_dm_addr),
				.master_response_put(dm_system_bus$master_response_put),
				.write_dm_addr(dm_system_bus$write_dm_addr),
				.write_dm_word(dm_system_bus$write_dm_word),
				.EN_reset(dm_system_bus$EN_reset),
				.EN_av_read(dm_system_bus$EN_av_read),
				.EN_write(dm_system_bus$EN_write),
				.EN_master_request_get(dm_system_bus$EN_master_request_get),
				.EN_master_response_put(dm_system_bus$EN_master_response_put),
				.RDY_reset(),
				.av_read(dm_system_bus$av_read),
				.RDY_av_read(dm_system_bus$RDY_av_read),
				.RDY_write(dm_system_bus$RDY_write),
				.master_request_get(dm_system_bus$master_request_get),
				.RDY_master_request_get(dm_system_bus$RDY_master_request_get),
				.RDY_master_response_put(dm_system_bus$RDY_master_response_put));

  // rule RL_rl_reset
  assign CAN_FIRE_RL_rl_reset = !dm_run_control$dmactive ;
  assign WILL_FIRE_RL_rl_reset = CAN_FIRE_RL_rl_reset && !EN_dmi_write ;

  // inlined wires
  assign f_read_addr_rv$port0__write_1 = { 1'd1, dmi_read_addr_dm_addr } ;
  assign f_read_addr_rv$port1__read =
	     EN_dmi_read_addr ?
	       f_read_addr_rv$port0__write_1 :
	       f_read_addr_rv ;
  assign f_read_addr_rv$port2__read =
	     EN_dmi_read_data ? 8'd42 : f_read_addr_rv$port1__read ;

  // register f_read_addr_rv
  assign f_read_addr_rv$D_IN = f_read_addr_rv$port2__read ;
  assign f_read_addr_rv$EN = 1'b1 ;

  // submodule dm_abstract_commands
  assign dm_abstract_commands$av_read_dm_addr =
	     f_read_addr_rv$port1__read[6:0] ;
  assign dm_abstract_commands$hart0_csr_mem_client_response_put =
	     hart0_hart_csr_mem_client_response_put ;
  assign dm_abstract_commands$hart0_gpr_mem_client_response_put =
	     hart0_hart_gpr_mem_client_response_put ;
  assign dm_abstract_commands$write_dm_addr = dmi_write_dm_addr ;
  assign dm_abstract_commands$write_dm_word = dmi_write_dm_word ;
  assign dm_abstract_commands$EN_reset = WILL_FIRE_RL_rl_reset ;
  assign dm_abstract_commands$EN_av_read =
	     EN_dmi_read_data &&
	     (f_read_addr_rv$port1__read[6:0] == 7'h16 ||
	      f_read_addr_rv$port1__read[6:0] == 7'h17 ||
	      f_read_addr_rv$port1__read[6:0] == 7'h04 ||
	      f_read_addr_rv$port1__read[6:0] == 7'h05 ||
	      f_read_addr_rv$port1__read[6:0] == 7'h06 ||
	      f_read_addr_rv$port1__read[6:0] == 7'h07 ||
	      f_read_addr_rv$port1__read[6:0] == 7'h08 ||
	      f_read_addr_rv$port1__read[6:0] == 7'h09 ||
	      f_read_addr_rv$port1__read[6:0] == 7'h0A ||
	      f_read_addr_rv$port1__read[6:0] == 7'h0B ||
	      f_read_addr_rv$port1__read[6:0] == 7'h0C ||
	      f_read_addr_rv$port1__read[6:0] == 7'h0D ||
	      f_read_addr_rv$port1__read[6:0] == 7'h0F ||
	      f_read_addr_rv$port1__read[6:0] == 7'h18 ||
	      f_read_addr_rv$port1__read[6:0] == 7'h20) ;
  assign dm_abstract_commands$EN_write =
	     EN_dmi_write &&
	     (dmi_write_dm_addr == 7'h16 || dmi_write_dm_addr == 7'h17 ||
	      dmi_write_dm_addr == 7'h04 ||
	      dmi_write_dm_addr == 7'h05 ||
	      dmi_write_dm_addr == 7'h06 ||
	      dmi_write_dm_addr == 7'h07 ||
	      dmi_write_dm_addr == 7'h08 ||
	      dmi_write_dm_addr == 7'h09 ||
	      dmi_write_dm_addr == 7'h0A ||
	      dmi_write_dm_addr == 7'h0B ||
	      dmi_write_dm_addr == 7'h0C ||
	      dmi_write_dm_addr == 7'h0D ||
	      dmi_write_dm_addr == 7'h0F ||
	      dmi_write_dm_addr == 7'h18 ||
	      dmi_write_dm_addr == 7'h20) ;
  assign dm_abstract_commands$EN_hart0_gpr_mem_client_request_get =
	     EN_hart0_hart_gpr_mem_client_request_get ;
  assign dm_abstract_commands$EN_hart0_gpr_mem_client_response_put =
	     EN_hart0_hart_gpr_mem_client_response_put ;
  assign dm_abstract_commands$EN_hart0_csr_mem_client_request_get =
	     EN_hart0_hart_csr_mem_client_request_get ;
  assign dm_abstract_commands$EN_hart0_csr_mem_client_response_put =
	     EN_hart0_hart_csr_mem_client_response_put ;

  // submodule dm_run_control
  assign dm_run_control$av_read_dm_addr = f_read_addr_rv$port1__read[6:0] ;
  assign dm_run_control$hart0_client_run_halt_response_put =
	     hart0_hart_client_run_halt_response_put ;
  assign dm_run_control$hart0_reset_client_response_put =
	     hart0_hart_reset_client_response_put ;
  assign dm_run_control$ndm_reset_client_response_put =
	     ndm_reset_client_response_put ;
  assign dm_run_control$write_dm_addr = dmi_write_dm_addr ;
  assign dm_run_control$write_dm_word = dmi_write_dm_word ;
  assign dm_run_control$EN_reset = WILL_FIRE_RL_rl_reset ;
  assign dm_run_control$EN_av_read =
	     EN_dmi_read_data &&
	     (f_read_addr_rv$port1__read[6:0] == 7'h10 ||
	      f_read_addr_rv$port1__read[6:0] == 7'h11 ||
	      f_read_addr_rv$port1__read[6:0] == 7'h12 ||
	      f_read_addr_rv$port1__read[6:0] == 7'h13 ||
	      f_read_addr_rv$port1__read[6:0] == 7'h14 ||
	      f_read_addr_rv$port1__read[6:0] == 7'h15 ||
	      f_read_addr_rv$port1__read[6:0] == 7'h19 ||
	      f_read_addr_rv$port1__read[6:0] == 7'h30 ||
	      f_read_addr_rv$port1__read[6:0] == 7'h40 ||
	      f_read_addr_rv$port1__read[6:0] == 7'h5F ||
	      f_read_addr_rv$port1__read[6:0] == 7'h60) ;
  assign dm_run_control$EN_write =
	     EN_dmi_write &&
	     (dmi_write_dm_addr == 7'h10 || dmi_write_dm_addr == 7'h11 ||
	      dmi_write_dm_addr == 7'h12 ||
	      dmi_write_dm_addr == 7'h13 ||
	      dmi_write_dm_addr == 7'h14 ||
	      dmi_write_dm_addr == 7'h15 ||
	      dmi_write_dm_addr == 7'h19 ||
	      dmi_write_dm_addr == 7'h30 ||
	      dmi_write_dm_addr == 7'h40 ||
	      dmi_write_dm_addr == 7'h5F ||
	      dmi_write_dm_addr == 7'h60) ;
  assign dm_run_control$EN_hart0_reset_client_request_get =
	     EN_hart0_hart_reset_client_request_get ;
  assign dm_run_control$EN_hart0_reset_client_response_put =
	     EN_hart0_hart_reset_client_response_put ;
  assign dm_run_control$EN_hart0_client_run_halt_request_get =
	     EN_hart0_hart_client_run_halt_request_get ;
  assign dm_run_control$EN_hart0_client_run_halt_response_put =
	     EN_hart0_hart_client_run_halt_response_put ;
  assign dm_run_control$EN_hart0_get_other_req_get =
	     EN_hart0_hart_get_other_req_get ;
  assign dm_run_control$EN_ndm_reset_client_request_get =
	     EN_ndm_reset_client_request_get ;
  assign dm_run_control$EN_ndm_reset_client_response_put =
	     EN_ndm_reset_client_response_put ;

  // submodule dm_system_bus
  assign dm_system_bus$av_read_dm_addr = f_read_addr_rv$port1__read[6:0] ;
  assign dm_system_bus$master_response_put = sb_client_response_put ;
  assign dm_system_bus$write_dm_addr = dmi_write_dm_addr ;
  assign dm_system_bus$write_dm_word = dmi_write_dm_word ;
  assign dm_system_bus$EN_reset = WILL_FIRE_RL_rl_reset ;
  assign dm_system_bus$EN_av_read =
	     EN_dmi_read_data &&
	     (f_read_addr_rv$port1__read[6:0] == 7'h38 ||
	      f_read_addr_rv$port1__read[6:0] == 7'h39 ||
	      f_read_addr_rv$port1__read[6:0] == 7'h3A ||
	      f_read_addr_rv$port1__read[6:0] == 7'h3B ||
	      f_read_addr_rv$port1__read[6:0] == 7'h3C ||
	      f_read_addr_rv$port1__read[6:0] == 7'h3D ||
	      f_read_addr_rv$port1__read[6:0] == 7'h3E ||
	      f_read_addr_rv$port1__read[6:0] == 7'h3F) ;
  assign dm_system_bus$EN_write =
	     EN_dmi_write &&
	     (dmi_write_dm_addr == 7'h38 || dmi_write_dm_addr == 7'h39 ||
	      dmi_write_dm_addr == 7'h3A ||
	      dmi_write_dm_addr == 7'h3B ||
	      dmi_write_dm_addr == 7'h3C ||
	      dmi_write_dm_addr == 7'h3D ||
	      dmi_write_dm_addr == 7'h3E ||
	      dmi_write_dm_addr == 7'h3F) ;
  assign dm_system_bus$EN_master_request_get = EN_sb_client_request_get ;
  assign dm_system_bus$EN_master_response_put = EN_sb_client_response_put ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        f_read_addr_rv <= `BSV_ASSIGNMENT_DELAY 8'd42;
      end
    else
      begin
        if (f_read_addr_rv$EN)
	  f_read_addr_rv <= `BSV_ASSIGNMENT_DELAY f_read_addr_rv$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    f_read_addr_rv = 8'hAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_reset)
	begin
	  v__h544 = $stime;
	  #0;
	end
    v__h538 = v__h544 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_reset) $display("%0d: Debug_Module reset", v__h538);
  end
  // synopsys translate_on
endmodule  // mkDebug_Module

